"""Initial migration.

Revision ID: 48382b10da56
Revises: 
Create Date: 2024-08-29 11:48:47.396377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48382b10da56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('user_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meta', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
