"""Customer Data inserted at User Meta table

Revision ID: c25316a71396
Revises: 14874e2bafe1
Create Date: 2024-09-06 18:02:02.006979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25316a71396'
down_revision = '14874e2bafe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('customer_phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meta', schema=None) as batch_op:
        batch_op.drop_column('customer_country')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_phone_number')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
